#!/usr/bin/env node

console.log('hello world');
const fs = require('fs');
const { syncBuiltinESMExports } = require('module');
const { createSpinner } = require('nanospinner');


function worker() {
   
const sleep= (ms = 10000) => new Promise((r) => setTimeout(r, ms));

if(process.argv[2] != "" && process.argv[3] != "" && process.argv[4] == "--normal") {
   const spinner = createSpinner('Writing A Normal File.....').start();

   setTimeout(() => {
      spinner.success({ text: `Successfully Created A ${process.argv[3]}.js file! ` });
   }, 2000);
     fs.writeFileSync(`${process.argv[3]}.js`,`fetch('${process.argv[2]}')
     .then(res => res.json())
     .then(data => {
      console.log(data);
     })`);
}

else if(process.argv[2] != "" && process.argv[3] != "" && process.argv[4] == "node-fetch") {
   const fs = require('fs');

   const spinner = createSpinner('Writing A Node-Fetch+ File.....').start();

   setTimeout(() => {
      spinner.success({ text: `Successfully Created A ${process.argv[3]}.js file! ` });
   }, 2000);

   fs.writeFileSync(`${process.argv[3]}.js`,`//please install node-fetch before running this program.

   const fetch = require('node-fetch');
   fetch('${process.argv[2]}')
     .then(res => res.json())
     .then(data => {
      console.log(data);
     })`);
}
else if(process.argv[2] == "puppeteer") {
   const spinner = createSpinner('Installing Puppeteer for you....').start();

   setTimeout(() => {
      spinner.success({ text: `Successfully Created A Puppeteer.js file! ` });
   }, 2000);
  
   fs.writeFileSync(`puppeteer.js`,"")
}
}
worker();

module.exports = worker;
